/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as ApadTokenContractJson } from "../ApadToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace ApadTokenTypes {
  export type Fields = {
    maxSupply: bigint;
    burned: bigint;
  };

  export type State = ContractState<Fields>;

  export type BurnEvent = ContractEvent<{ burner: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    burn: {
      params: CallContractParams<{ from: Address; amount: bigint }>;
      result: CallContractResult<null>;
    };
    getMaxSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    burn: {
      params: SignExecuteContractMethodParams<{
        from: Address;
        amount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getMaxSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  ApadTokenInstance,
  ApadTokenTypes.Fields
> {
  encodeFields(fields: ApadTokenTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as ApadTokenTypes.Fields;
  }

  eventIndex = { Burn: 0 };

  at(address: string): ApadTokenInstance {
    return new ApadTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<ApadTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<ApadTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<ApadTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<ApadTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    burn: async (
      params: TestContractParamsWithoutMaps<
        ApadTokenTypes.Fields,
        { from: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burn", params, getContractByCodeHash);
    },
    getMaxSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<ApadTokenTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMaxSupply", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const ApadToken = new Factory(
  Contract.fromJson(
    ApadTokenContractJson,
    "",
    "da7543ebc9e29ae7fe1d75043dedead5564b44998b4f5076c4eee829bc814ca3",
    []
  )
);

// Use this class to interact with the blockchain
export class ApadTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ApadTokenTypes.State> {
    return fetchContractState(ApadToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBurnEvent(
    options: EventSubscribeOptions<ApadTokenTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ApadToken.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  methods = {
    getSymbol: async (
      params?: ApadTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<ApadTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        ApadToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: ApadTokenTypes.CallMethodParams<"getName">
    ): Promise<ApadTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        ApadToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: ApadTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<ApadTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        ApadToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: ApadTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<ApadTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        ApadToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    burn: async (
      params: ApadTokenTypes.CallMethodParams<"burn">
    ): Promise<ApadTokenTypes.CallMethodResult<"burn">> => {
      return callMethod(ApadToken, this, "burn", params, getContractByCodeHash);
    },
    getMaxSupply: async (
      params?: ApadTokenTypes.CallMethodParams<"getMaxSupply">
    ): Promise<ApadTokenTypes.CallMethodResult<"getMaxSupply">> => {
      return callMethod(
        ApadToken,
        this,
        "getMaxSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  view = this.methods;

  transact = {
    getSymbol: async (
      params: ApadTokenTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<ApadTokenTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(ApadToken, this, "getSymbol", params);
    },
    getName: async (
      params: ApadTokenTypes.SignExecuteMethodParams<"getName">
    ): Promise<ApadTokenTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(ApadToken, this, "getName", params);
    },
    getDecimals: async (
      params: ApadTokenTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<ApadTokenTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(ApadToken, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: ApadTokenTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<ApadTokenTypes.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(ApadToken, this, "getTotalSupply", params);
    },
    burn: async (
      params: ApadTokenTypes.SignExecuteMethodParams<"burn">
    ): Promise<ApadTokenTypes.SignExecuteMethodResult<"burn">> => {
      return signExecuteMethod(ApadToken, this, "burn", params);
    },
    getMaxSupply: async (
      params: ApadTokenTypes.SignExecuteMethodParams<"getMaxSupply">
    ): Promise<ApadTokenTypes.SignExecuteMethodResult<"getMaxSupply">> => {
      return signExecuteMethod(ApadToken, this, "getMaxSupply", params);
    },
  };

  async multicall<Calls extends ApadTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ApadTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      ApadToken,
      this,
      calls,
      getContractByCodeHash
    )) as ApadTokenTypes.MultiCallResults<Calls>;
  }
}
