/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
} from "@alephium/web3";
import { default as ApadTokenContractJson } from "../ApadToken.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace ApadTokenTypes {
  export type Fields = {
    minted: boolean;
    burned: bigint;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{ to: Address; amount: bigint }>;
  export type BurnEvent = ContractEvent<{ burner: Address; amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getMaxSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
}

class Factory extends ContractFactory<
  ApadTokenInstance,
  ApadTokenTypes.Fields
> {
  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as ApadTokenTypes.Fields;
  }

  eventIndex = { Mint: 0, Burn: 1 };
  consts = { ErrorCodes: { TokensAlreadyMinted: BigInt(0) } };

  at(address: string): ApadTokenInstance {
    return new ApadTokenInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<TestContractParams<ApadTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getSymbol", params);
    },
    getName: async (
      params: Omit<TestContractParams<ApadTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<HexString>> => {
      return testMethod(this, "getName", params);
    },
    getDecimals: async (
      params: Omit<TestContractParams<ApadTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: Omit<TestContractParams<ApadTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getTotalSupply", params);
    },
    mint: async (
      params: TestContractParams<ApadTokenTypes.Fields, { to: Address }>
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "mint", params);
    },
    burn: async (
      params: TestContractParams<
        ApadTokenTypes.Fields,
        { from: Address; amount: bigint }
      >
    ): Promise<TestContractResult<null>> => {
      return testMethod(this, "burn", params);
    },
    getMaxSupply: async (
      params: Omit<TestContractParams<ApadTokenTypes.Fields, never>, "testArgs">
    ): Promise<TestContractResult<bigint>> => {
      return testMethod(this, "getMaxSupply", params);
    },
  };
}

// Use this object to test and deploy the contract
export const ApadToken = new Factory(
  Contract.fromJson(
    ApadTokenContractJson,
    "",
    "6d112e61a19cec16aef23ad92eacc8f143eb56d8c9055f69b1bdb9a310d31b99"
  )
);

// Use this class to interact with the blockchain
export class ApadTokenInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<ApadTokenTypes.State> {
    return fetchContractState(ApadToken, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<ApadTokenTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ApadToken.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  subscribeBurnEvent(
    options: EventSubscribeOptions<ApadTokenTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      ApadToken.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      ApadTokenTypes.MintEvent | ApadTokenTypes.BurnEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      ApadToken.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    getSymbol: async (
      params?: ApadTokenTypes.CallMethodParams<"getSymbol">
    ): Promise<ApadTokenTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        ApadToken,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: ApadTokenTypes.CallMethodParams<"getName">
    ): Promise<ApadTokenTypes.CallMethodResult<"getName">> => {
      return callMethod(
        ApadToken,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: ApadTokenTypes.CallMethodParams<"getDecimals">
    ): Promise<ApadTokenTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        ApadToken,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: ApadTokenTypes.CallMethodParams<"getTotalSupply">
    ): Promise<ApadTokenTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        ApadToken,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMaxSupply: async (
      params?: ApadTokenTypes.CallMethodParams<"getMaxSupply">
    ): Promise<ApadTokenTypes.CallMethodResult<"getMaxSupply">> => {
      return callMethod(
        ApadToken,
        this,
        "getMaxSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  async multicall<Calls extends ApadTokenTypes.MultiCallParams>(
    calls: Calls
  ): Promise<ApadTokenTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      ApadToken,
      this,
      calls,
      getContractByCodeHash
    )) as ApadTokenTypes.MultiCallResults<Calls>;
  }
}
