/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as SaleBuyerAccountContractJson } from "../launch_sale/generic/SaleBuyerAccount.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace SaleBuyerAccountTypes {
  export type Fields = {
    parentContractAddress: Address;
    accountHolder: Address;
    amountBuy: bigint;
    amountBid: bigint;
    amountClaimed: bigint;
    amountClaimedRefund: bigint;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    destroy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    isSafeToDestroy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    getParentContractAddress: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getAccountHolder: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    buy: {
      params: CallContractParams<{
        addAmountBuy: bigint;
        addAmountBid: bigint;
      }>;
      result: CallContractResult<null>;
    };
    claim: {
      params: CallContractParams<{ claimAmount: bigint }>;
      result: CallContractResult<null>;
    };
    claimRefund: {
      params: CallContractParams<{ claimAmount: bigint }>;
      result: CallContractResult<null>;
    };
    getAmountBuy: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAmountBid: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAmountClaimed: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getAmountClaimedRefund: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    destroy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isSafeToDestroy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getParentContractAddress: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAccountHolder: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    buy: {
      params: SignExecuteContractMethodParams<{
        addAmountBuy: bigint;
        addAmountBid: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    claim: {
      params: SignExecuteContractMethodParams<{ claimAmount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    claimRefund: {
      params: SignExecuteContractMethodParams<{ claimAmount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getAmountBuy: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAmountBid: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAmountClaimed: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getAmountClaimedRefund: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  SaleBuyerAccountInstance,
  SaleBuyerAccountTypes.Fields
> {
  encodeFields(fields: SaleBuyerAccountTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as SaleBuyerAccountTypes.Fields;
  }

  consts = {
    ErrorCodes: {
      ClaimMoreThanBuy: BigInt(1101),
      ClaimMoreThanBid: BigInt(1102),
    },
    AccountBaseErrorCodes: {
      UnauthorizedAccess: BigInt(12101),
      UnsafeDestroy: BigInt(12102),
    },
  };

  at(address: string): SaleBuyerAccountInstance {
    return new SaleBuyerAccountInstance(address);
  }

  tests = {
    destroy: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroy", params, getContractByCodeHash);
    },
    isSafeToDestroy: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isSafeToDestroy", params, getContractByCodeHash);
    },
    assertIsSafeToDestroy: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertIsSafeToDestroy",
        params,
        getContractByCodeHash
      );
    },
    assertIsParentTheCaller: async (
      params: TestContractParamsWithoutMaps<
        SaleBuyerAccountTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertIsParentTheCaller",
        params,
        getContractByCodeHash
      );
    },
    getParentContractAddress: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(
        this,
        "getParentContractAddress",
        params,
        getContractByCodeHash
      );
    },
    getAccountHolder: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(
        this,
        "getAccountHolder",
        params,
        getContractByCodeHash
      );
    },
    buy: async (
      params: TestContractParamsWithoutMaps<
        SaleBuyerAccountTypes.Fields,
        { addAmountBuy: bigint; addAmountBid: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "buy", params, getContractByCodeHash);
    },
    claim: async (
      params: TestContractParamsWithoutMaps<
        SaleBuyerAccountTypes.Fields,
        { claimAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claim", params, getContractByCodeHash);
    },
    claimRefund: async (
      params: TestContractParamsWithoutMaps<
        SaleBuyerAccountTypes.Fields,
        { claimAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimRefund", params, getContractByCodeHash);
    },
    getAmountBuy: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getAmountBuy", params, getContractByCodeHash);
    },
    getAmountBid: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getAmountBid", params, getContractByCodeHash);
    },
    getAmountClaimed: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getAmountClaimed",
        params,
        getContractByCodeHash
      );
    },
    getAmountClaimedRefund: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleBuyerAccountTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getAmountClaimedRefund",
        params,
        getContractByCodeHash
      );
    },
  };
}

// Use this object to test and deploy the contract
export const SaleBuyerAccount = new Factory(
  Contract.fromJson(
    SaleBuyerAccountContractJson,
    "",
    "5b85bbcf941c0e29fa634eccc5c21a0545245218348b1c27c9c7fc3980f5913a",
    []
  )
);

// Use this class to interact with the blockchain
export class SaleBuyerAccountInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SaleBuyerAccountTypes.State> {
    return fetchContractState(SaleBuyerAccount, this);
  }

  methods = {
    destroy: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"destroy">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"destroy">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "destroy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isSafeToDestroy: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"isSafeToDestroy">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"isSafeToDestroy">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "isSafeToDestroy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getParentContractAddress: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"getParentContractAddress">
    ): Promise<
      SaleBuyerAccountTypes.CallMethodResult<"getParentContractAddress">
    > => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "getParentContractAddress",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAccountHolder: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"getAccountHolder">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"getAccountHolder">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "getAccountHolder",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    buy: async (
      params: SaleBuyerAccountTypes.CallMethodParams<"buy">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"buy">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "buy",
        params,
        getContractByCodeHash
      );
    },
    claim: async (
      params: SaleBuyerAccountTypes.CallMethodParams<"claim">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"claim">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "claim",
        params,
        getContractByCodeHash
      );
    },
    claimRefund: async (
      params: SaleBuyerAccountTypes.CallMethodParams<"claimRefund">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"claimRefund">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "claimRefund",
        params,
        getContractByCodeHash
      );
    },
    getAmountBuy: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"getAmountBuy">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"getAmountBuy">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "getAmountBuy",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAmountBid: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"getAmountBid">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"getAmountBid">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "getAmountBid",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAmountClaimed: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"getAmountClaimed">
    ): Promise<SaleBuyerAccountTypes.CallMethodResult<"getAmountClaimed">> => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "getAmountClaimed",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getAmountClaimedRefund: async (
      params?: SaleBuyerAccountTypes.CallMethodParams<"getAmountClaimedRefund">
    ): Promise<
      SaleBuyerAccountTypes.CallMethodResult<"getAmountClaimedRefund">
    > => {
      return callMethod(
        SaleBuyerAccount,
        this,
        "getAmountClaimedRefund",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  view = this.methods;

  transact = {
    destroy: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"destroy">
    ): Promise<SaleBuyerAccountTypes.SignExecuteMethodResult<"destroy">> => {
      return signExecuteMethod(SaleBuyerAccount, this, "destroy", params);
    },
    isSafeToDestroy: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"isSafeToDestroy">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"isSafeToDestroy">
    > => {
      return signExecuteMethod(
        SaleBuyerAccount,
        this,
        "isSafeToDestroy",
        params
      );
    },
    getParentContractAddress: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"getParentContractAddress">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"getParentContractAddress">
    > => {
      return signExecuteMethod(
        SaleBuyerAccount,
        this,
        "getParentContractAddress",
        params
      );
    },
    getAccountHolder: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"getAccountHolder">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"getAccountHolder">
    > => {
      return signExecuteMethod(
        SaleBuyerAccount,
        this,
        "getAccountHolder",
        params
      );
    },
    buy: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"buy">
    ): Promise<SaleBuyerAccountTypes.SignExecuteMethodResult<"buy">> => {
      return signExecuteMethod(SaleBuyerAccount, this, "buy", params);
    },
    claim: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"claim">
    ): Promise<SaleBuyerAccountTypes.SignExecuteMethodResult<"claim">> => {
      return signExecuteMethod(SaleBuyerAccount, this, "claim", params);
    },
    claimRefund: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"claimRefund">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"claimRefund">
    > => {
      return signExecuteMethod(SaleBuyerAccount, this, "claimRefund", params);
    },
    getAmountBuy: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"getAmountBuy">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"getAmountBuy">
    > => {
      return signExecuteMethod(SaleBuyerAccount, this, "getAmountBuy", params);
    },
    getAmountBid: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"getAmountBid">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"getAmountBid">
    > => {
      return signExecuteMethod(SaleBuyerAccount, this, "getAmountBid", params);
    },
    getAmountClaimed: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"getAmountClaimed">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"getAmountClaimed">
    > => {
      return signExecuteMethod(
        SaleBuyerAccount,
        this,
        "getAmountClaimed",
        params
      );
    },
    getAmountClaimedRefund: async (
      params: SaleBuyerAccountTypes.SignExecuteMethodParams<"getAmountClaimedRefund">
    ): Promise<
      SaleBuyerAccountTypes.SignExecuteMethodResult<"getAmountClaimedRefund">
    > => {
      return signExecuteMethod(
        SaleBuyerAccount,
        this,
        "getAmountClaimedRefund",
        params
      );
    },
  };

  async multicall<Calls extends SaleBuyerAccountTypes.MultiCallParams>(
    calls: Calls
  ): Promise<SaleBuyerAccountTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      SaleBuyerAccount,
      this,
      calls,
      getContractByCodeHash
    )) as SaleBuyerAccountTypes.MultiCallResults<Calls>;
  }
}
