/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as SaleFlatPriceAlphV3ContractJson } from "../launch_sale_v3/SaleFlatPriceAlphV3.ral.json";
import { getContractByCodeHash } from "./contracts";
import { ListingRecord, AllStructs } from "./types";

// Custom types for the contract
export namespace SaleFlatPriceAlphV3Types {
  export type Fields = {
    rewardDistributor: HexString;
    saleOwner: Address;
    accountTemplateId: HexString;
    tokenPrice: bigint;
    minRaise: bigint;
    maxRaise: bigint;
    saleTokenId: HexString;
    saleTokenTotalAmount: bigint;
    bidTokenId: HexString;
    saleStart: bigint;
    saleEnd: bigint;
    whitelistSaleStart: bigint;
    whitelistSaleEnd: bigint;
    tokensSold: bigint;
    totalRaised: bigint;
    merkleRoot: HexString;
    publicSaleMaxBid: bigint;
    sellerClaimed: bigint;
    upfrontRelease: bigint;
    vestingEnd: bigint;
    cliffEnd: bigint;
  };

  export type State = ContractState<Fields>;

  export type BuyEvent = ContractEvent<{
    account: Address;
    buyBidAmount: bigint;
    buyTokenAmount: bigint;
  }>;
  export type UpdateWhitelistBuyerMaxBidEvent = ContractEvent<{
    caller: Address;
    newPublicSaleMaxBid: bigint;
    oldPublicSaleMaxBid: bigint;
  }>;
  export type UpdatePublicSaleMaxBidEvent = ContractEvent<{
    caller: Address;
    newSellerClaimed: bigint;
    oldSellerClaimed: bigint;
  }>;
  export type UpdateUpfrontReleaseEvent = ContractEvent<{
    caller: Address;
    newUpfrontRelease: bigint;
    oldUpfrontRelease: bigint;
  }>;
  export type UpdateVestingEndEvent = ContractEvent<{
    caller: Address;
    newVestingEnd: bigint;
    oldVestingEnd: bigint;
  }>;
  export type UpdateCliffEndEvent = ContractEvent<{
    caller: Address;
    newCliffEnd: bigint;
    oldCliffEnd: bigint;
  }>;
  export type AccountCreateEvent = ContractEvent<{
    account: Address;
    contractId: HexString;
  }>;
  export type AccountDestroyEvent = ContractEvent<{
    account: Address;
    contractId: HexString;
  }>;
  export type ClaimBuyerEvent = ContractEvent<{
    account: Address;
    saleTokenAmount: bigint;
  }>;
  export type ClaimBuyerRefundEvent = ContractEvent<{
    account: Address;
    bidTokenAmount: bigint;
  }>;
  export type ClaimSellerEvent = ContractEvent<{
    account: Address;
    bidTokenAmount: bigint;
  }>;
  export type ClaimSellerRefundEvent = ContractEvent<{
    account: Address;
    saleTokenAmount: bigint;
  }>;
  export type SaleDatesUpdateEvent = ContractEvent<{
    caller: Address;
    newSaleStartDate: bigint;
    oldSaleStartDate: bigint;
    newSaleEndDate: bigint;
    oldSaleEndDate: bigint;
  }>;
  export type WhitelistSaleDatesUpdateEvent = ContractEvent<{
    caller: Address;
    newWLSaleStartDate: bigint;
    oldWLSaleStartDate: bigint;
    newWLSaleEndDate: bigint;
    oldWLSaleEndDate: bigint;
  }>;
  export type UpdateRootEvent = ContractEvent<{
    newMerkleRoot: HexString;
    updatedBy: Address;
  }>;

  export interface CallMethodTable {
    buy: {
      params: CallContractParams<{
        bidAmount: bigint;
        wlPrice: bigint;
        wlMaxBid: bigint;
        wlMerkleProof: HexString;
        stateRentAmount: bigint;
      }>;
      result: CallContractResult<null>;
    };
    calculateClaimableAmount: {
      params: CallContractParams<{ buyerAccount: HexString }>;
      result: CallContractResult<bigint>;
    };
    calculateSaleTokensReceivedPerBidTokens: {
      params: CallContractParams<{ bidAmount: bigint; pricePerToken: bigint }>;
      result: CallContractResult<bigint>;
    };
    checkIsWhitelisted: {
      params: CallContractParams<{
        account: Address;
        wlMerkleProof: HexString;
        wlPrice: bigint;
        wlMaxBid: bigint;
      }>;
      result: CallContractResult<boolean>;
    };
    setAllFields: {
      params: CallContractParams<{
        newSaleStart: bigint;
        newSaleEnd: bigint;
        newWhitelistSaleStart: bigint;
        newWhitelistSaleEnd: bigint;
        newPublicSaleMaxBid: bigint;
        newUpfrontRelease: bigint;
        newVestingEnd: bigint;
        newCliffEnd: bigint;
      }>;
      result: CallContractResult<null>;
    };
    accountExists: {
      params: CallContractParams<{ account: Address }>;
      result: CallContractResult<boolean>;
    };
    getSubContractId: {
      params: CallContractParams<{ account: Address }>;
      result: CallContractResult<HexString>;
    };
    claim: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    claimRefund: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    setMerkleRoot: {
      params: CallContractParams<{ newMerkleRoot: HexString }>;
      result: CallContractResult<null>;
    };
    setSaleDates: {
      params: CallContractParams<{
        newSaleStart: bigint;
        newSaleEnd: bigint;
        newWhitelistSaleStart: bigint;
        newWhitelistSaleEnd: bigint;
      }>;
      result: CallContractResult<null>;
    };
    isSaleLive: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    isSaleFinished: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    isSaleSuccess: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    isWhitelistSaleLive: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    isWhitelistSale: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<boolean>;
    };
    isCallerSaleOwner: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<boolean>;
    };
    getSaleOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getSaleStart: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getSaleEnd: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getMinRaise: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getMaxRaise: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getSaleTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getBidTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getWhitelistSaleStart: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getWhitelistSaleEnd: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTokensSold: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalRaised: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getMerkleRoot: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> =
    Callss["length"] extends 1
      ? MultiCallResults<Callss[0]>
      : { [index in keyof Callss]: MultiCallResults<Callss[index]> };

  export interface SignExecuteMethodTable {
    buy: {
      params: SignExecuteContractMethodParams<{
        bidAmount: bigint;
        wlPrice: bigint;
        wlMaxBid: bigint;
        wlMerkleProof: HexString;
        stateRentAmount: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateClaimableAmount: {
      params: SignExecuteContractMethodParams<{ buyerAccount: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    calculateSaleTokensReceivedPerBidTokens: {
      params: SignExecuteContractMethodParams<{
        bidAmount: bigint;
        pricePerToken: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    checkIsWhitelisted: {
      params: SignExecuteContractMethodParams<{
        account: Address;
        wlMerkleProof: HexString;
        wlPrice: bigint;
        wlMaxBid: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    setAllFields: {
      params: SignExecuteContractMethodParams<{
        newSaleStart: bigint;
        newSaleEnd: bigint;
        newWhitelistSaleStart: bigint;
        newWhitelistSaleEnd: bigint;
        newPublicSaleMaxBid: bigint;
        newUpfrontRelease: bigint;
        newVestingEnd: bigint;
        newCliffEnd: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    accountExists: {
      params: SignExecuteContractMethodParams<{ account: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getSubContractId: {
      params: SignExecuteContractMethodParams<{ account: Address }>;
      result: SignExecuteScriptTxResult;
    };
    claim: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    claimRefund: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    setMerkleRoot: {
      params: SignExecuteContractMethodParams<{ newMerkleRoot: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    setSaleDates: {
      params: SignExecuteContractMethodParams<{
        newSaleStart: bigint;
        newSaleEnd: bigint;
        newWhitelistSaleStart: bigint;
        newWhitelistSaleEnd: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    isSaleLive: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isSaleFinished: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isSaleSuccess: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isWhitelistSaleLive: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isWhitelistSale: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    isCallerSaleOwner: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getSaleOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getSaleStart: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getSaleEnd: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getMinRaise: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getMaxRaise: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getSaleTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getBidTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getWhitelistSaleStart: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getWhitelistSaleEnd: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTokensSold: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalRaised: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getMerkleRoot: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  SaleFlatPriceAlphV3Instance,
  SaleFlatPriceAlphV3Types.Fields
> {
  encodeFields(fields: SaleFlatPriceAlphV3Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = {
    Buy: 0,
    UpdateWhitelistBuyerMaxBid: 1,
    UpdatePublicSaleMaxBid: 2,
    UpdateUpfrontRelease: 3,
    UpdateVestingEnd: 4,
    UpdateCliffEnd: 5,
    AccountCreate: 6,
    AccountDestroy: 7,
    ClaimBuyer: 8,
    ClaimBuyerRefund: 9,
    ClaimSeller: 10,
    ClaimSellerRefund: 11,
    SaleDatesUpdate: 12,
    WhitelistSaleDatesUpdate: 13,
    UpdateRoot: 14,
  };
  consts = {
    ErrorCodes: {
      PriceMoreThanMax: BigInt("601"),
      PriceLessThanMin: BigInt("602"),
      BidMoreThanMax: BigInt("603"),
      BidLessThanMin: BigInt("604"),
      InvalidClaimAmount: BigInt("605"),
      SaleTokenTotalExceeded: BigInt("606"),
      SaleOwnerCanNotBid: BigInt("607"),
      BuyerNotWhitelisted: BigInt("608"),
      SaleTokenMoreThan18Decimal: BigInt("609"),
      SaleAmountSmallerThanMin: BigInt("610"),
      SaleAmountLargerThanMax: BigInt("611"),
      SellerAlreadyClaimed: BigInt("612"),
      ClaimsNotStarted: BigInt("613"),
      UpfrontReleaseOutOfRange: BigInt("614"),
      VestingEndOutOfRange: BigInt("615"),
      CliffEndOutOfRange: BigInt("616"),
    },
    AccountErrorCodes: {
      AccountAlreadyExists: BigInt("12001"),
      AccountDoesNotExists: BigInt("12002"),
    },
    SaleBaseErrorCodes: {
      SaleNotLive: BigInt("1001"),
      SaleNotFinished: BigInt("1002"),
      SaleClaimNotAvailable: BigInt("1003"),
      SaleRefundNotAvailable: BigInt("1004"),
      SaleCanNotBeEditedAtThisTime: BigInt("1005"),
      SaleUpdateUnauthorized: BigInt("1006"),
      SaleIsNotWLSale: BigInt("1007"),
      SaleStartMustBeInFuture: BigInt("1008"),
      SaleEndMustBeAfterSaleStart: BigInt("1009"),
      WLSaleStartMustBeWithinSaleDates: BigInt("1010"),
      WLSaleEndMustBeWithinSaleDatesAndAfterWLSaleStart: BigInt("1011"),
      InvalidMerkleRoot: BigInt("1012"),
    },
    MerkleProofErrorCodes: {
      InvalidProofSize: BigInt("11001"),
      InvalidDataHash: BigInt("11002"),
    },
  };

  at(address: string): SaleFlatPriceAlphV3Instance {
    return new SaleFlatPriceAlphV3Instance(address);
  }

  tests = {
    claimBuyer: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { caller: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimBuyer", params, getContractByCodeHash);
    },
    claimBuyerRefund: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { caller: Address; amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "claimBuyerRefund",
        params,
        getContractByCodeHash
      );
    },
    claimSeller: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimSeller", params, getContractByCodeHash);
    },
    claimSellerRefund: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "claimSellerRefund",
        params,
        getContractByCodeHash
      );
    },
    buy: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        {
          bidAmount: bigint;
          wlPrice: bigint;
          wlMaxBid: bigint;
          wlMerkleProof: HexString;
          stateRentAmount: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "buy", params, getContractByCodeHash);
    },
    checkBidLimit: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { account: Address; bidAmount: bigint; maxBid: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "checkBidLimit", params, getContractByCodeHash);
    },
    calculateClaimableAmount: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { buyerAccount: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateClaimableAmount",
        params,
        getContractByCodeHash
      );
    },
    calculateSaleTokensReceivedPerBidTokens: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { bidAmount: bigint; pricePerToken: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateSaleTokensReceivedPerBidTokens",
        params,
        getContractByCodeHash
      );
    },
    checkIsWhitelisted: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        {
          account: Address;
          wlMerkleProof: HexString;
          wlPrice: bigint;
          wlMaxBid: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "checkIsWhitelisted",
        params,
        getContractByCodeHash
      );
    },
    setAllFields: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        {
          newSaleStart: bigint;
          newSaleEnd: bigint;
          newWhitelistSaleStart: bigint;
          newWhitelistSaleEnd: bigint;
          newPublicSaleMaxBid: bigint;
          newUpfrontRelease: bigint;
          newVestingEnd: bigint;
          newCliffEnd: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setAllFields", params, getContractByCodeHash);
    },
    assertPriceInRange: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertPriceInRange",
        params,
        getContractByCodeHash
      );
    },
    assertMaxBidAmountInRange: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { maxBidAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertMaxBidAmountInRange",
        params,
        getContractByCodeHash
      );
    },
    assertBidAmountInRange: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { bidAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertBidAmountInRange",
        params,
        getContractByCodeHash
      );
    },
    assertSaleAmountInRange: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertSaleAmountInRange",
        params,
        getContractByCodeHash
      );
    },
    createAccount: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        {
          account: Address;
          encodedImmFields: HexString;
          encodedMutFields: HexString;
          stateRentAmount: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "createAccount", params, getContractByCodeHash);
    },
    destroyAccount: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { account: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "destroyAccount", params, getContractByCodeHash);
    },
    assertAccountExists: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { account: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertAccountExists",
        params,
        getContractByCodeHash
      );
    },
    accountExists: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { account: Address }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "accountExists", params, getContractByCodeHash);
    },
    getSubContractId: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { account: Address }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getSubContractId",
        params,
        getContractByCodeHash
      );
    },
    claim: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claim", params, getContractByCodeHash);
    },
    claimRefund: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimRefund", params, getContractByCodeHash);
    },
    setMerkleRoot: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { newMerkleRoot: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setMerkleRoot", params, getContractByCodeHash);
    },
    setSaleDates: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        {
          newSaleStart: bigint;
          newSaleEnd: bigint;
          newWhitelistSaleStart: bigint;
          newWhitelistSaleEnd: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setSaleDates", params, getContractByCodeHash);
    },
    assertSaleLive: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "assertSaleLive", params, getContractByCodeHash);
    },
    assertSaleFinished: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertSaleFinished",
        params,
        getContractByCodeHash
      );
    },
    assertCanClaim: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "assertCanClaim", params, getContractByCodeHash);
    },
    assertCanClaimRefund: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertCanClaimRefund",
        params,
        getContractByCodeHash
      );
    },
    assertSaleEditable: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertSaleEditable",
        params,
        getContractByCodeHash
      );
    },
    assertValidSaleDates: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { asSaleStart: bigint; asSaleEnd: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertValidSaleDates",
        params,
        getContractByCodeHash
      );
    },
    assertValidWLSaleDates: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        {
          asSaleStart: bigint;
          asSaleEnd: bigint;
          asWLSaleStart: bigint;
          asWLSaleEnd: bigint;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertValidWLSaleDates",
        params,
        getContractByCodeHash
      );
    },
    isSaleLive: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isSaleLive", params, getContractByCodeHash);
    },
    isSaleFinished: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isSaleFinished", params, getContractByCodeHash);
    },
    isSaleSuccess: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isSaleSuccess", params, getContractByCodeHash);
    },
    isWhitelistSaleLive: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "isWhitelistSaleLive",
        params,
        getContractByCodeHash
      );
    },
    isWhitelistSale: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "isWhitelistSale", params, getContractByCodeHash);
    },
    isCallerSaleOwner: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "isCallerSaleOwner",
        params,
        getContractByCodeHash
      );
    },
    getSaleOwner: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getSaleOwner", params, getContractByCodeHash);
    },
    getSaleStart: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getSaleStart", params, getContractByCodeHash);
    },
    getSaleEnd: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getSaleEnd", params, getContractByCodeHash);
    },
    getMinRaise: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMinRaise", params, getContractByCodeHash);
    },
    getMaxRaise: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMaxRaise", params, getContractByCodeHash);
    },
    getSaleTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSaleTokenId", params, getContractByCodeHash);
    },
    getBidTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getBidTokenId", params, getContractByCodeHash);
    },
    getWhitelistSaleStart: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getWhitelistSaleStart",
        params,
        getContractByCodeHash
      );
    },
    getWhitelistSaleEnd: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getWhitelistSaleEnd",
        params,
        getContractByCodeHash
      );
    },
    getTokensSold: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTokensSold", params, getContractByCodeHash);
    },
    getTotalRaised: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalRaised", params, getContractByCodeHash);
    },
    getMerkleRoot: async (
      params: Omit<
        TestContractParamsWithoutMaps<SaleFlatPriceAlphV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getMerkleRoot", params, getContractByCodeHash);
    },
    updateRoot: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { newMerkleRoot: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateRoot", params, getContractByCodeHash);
    },
    verify: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { proof: HexString; dataHash: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "verify", params, getContractByCodeHash);
    },
    hashPair: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { a: HexString; b: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "hashPair", params, getContractByCodeHash);
    },
    hash: async (
      params: TestContractParamsWithoutMaps<
        SaleFlatPriceAlphV3Types.Fields,
        { dataToHash: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "hash", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const SaleFlatPriceAlphV3 = new Factory(
  Contract.fromJson(
    SaleFlatPriceAlphV3ContractJson,
    "",
    "f4faf01feb07f51142ee3b799a9e5b9581d59c765e7b054add11342210e7d18c",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class SaleFlatPriceAlphV3Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<SaleFlatPriceAlphV3Types.State> {
    return fetchContractState(SaleFlatPriceAlphV3, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeBuyEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.BuyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "Buy",
      fromCount
    );
  }

  subscribeUpdateWhitelistBuyerMaxBidEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.UpdateWhitelistBuyerMaxBidEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "UpdateWhitelistBuyerMaxBid",
      fromCount
    );
  }

  subscribeUpdatePublicSaleMaxBidEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.UpdatePublicSaleMaxBidEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "UpdatePublicSaleMaxBid",
      fromCount
    );
  }

  subscribeUpdateUpfrontReleaseEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.UpdateUpfrontReleaseEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "UpdateUpfrontRelease",
      fromCount
    );
  }

  subscribeUpdateVestingEndEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.UpdateVestingEndEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "UpdateVestingEnd",
      fromCount
    );
  }

  subscribeUpdateCliffEndEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.UpdateCliffEndEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "UpdateCliffEnd",
      fromCount
    );
  }

  subscribeAccountCreateEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.AccountCreateEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "AccountCreate",
      fromCount
    );
  }

  subscribeAccountDestroyEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.AccountDestroyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "AccountDestroy",
      fromCount
    );
  }

  subscribeClaimBuyerEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.ClaimBuyerEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "ClaimBuyer",
      fromCount
    );
  }

  subscribeClaimBuyerRefundEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.ClaimBuyerRefundEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "ClaimBuyerRefund",
      fromCount
    );
  }

  subscribeClaimSellerEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.ClaimSellerEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "ClaimSeller",
      fromCount
    );
  }

  subscribeClaimSellerRefundEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.ClaimSellerRefundEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "ClaimSellerRefund",
      fromCount
    );
  }

  subscribeSaleDatesUpdateEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.SaleDatesUpdateEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "SaleDatesUpdate",
      fromCount
    );
  }

  subscribeWhitelistSaleDatesUpdateEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.WhitelistSaleDatesUpdateEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "WhitelistSaleDatesUpdate",
      fromCount
    );
  }

  subscribeUpdateRootEvent(
    options: EventSubscribeOptions<SaleFlatPriceAlphV3Types.UpdateRootEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      "UpdateRoot",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | SaleFlatPriceAlphV3Types.BuyEvent
      | SaleFlatPriceAlphV3Types.UpdateWhitelistBuyerMaxBidEvent
      | SaleFlatPriceAlphV3Types.UpdatePublicSaleMaxBidEvent
      | SaleFlatPriceAlphV3Types.UpdateUpfrontReleaseEvent
      | SaleFlatPriceAlphV3Types.UpdateVestingEndEvent
      | SaleFlatPriceAlphV3Types.UpdateCliffEndEvent
      | SaleFlatPriceAlphV3Types.AccountCreateEvent
      | SaleFlatPriceAlphV3Types.AccountDestroyEvent
      | SaleFlatPriceAlphV3Types.ClaimBuyerEvent
      | SaleFlatPriceAlphV3Types.ClaimBuyerRefundEvent
      | SaleFlatPriceAlphV3Types.ClaimSellerEvent
      | SaleFlatPriceAlphV3Types.ClaimSellerRefundEvent
      | SaleFlatPriceAlphV3Types.SaleDatesUpdateEvent
      | SaleFlatPriceAlphV3Types.WhitelistSaleDatesUpdateEvent
      | SaleFlatPriceAlphV3Types.UpdateRootEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      SaleFlatPriceAlphV3.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    buy: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"buy">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"buy">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "buy",
        params,
        getContractByCodeHash
      );
    },
    calculateClaimableAmount: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"calculateClaimableAmount">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"calculateClaimableAmount">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "calculateClaimableAmount",
        params,
        getContractByCodeHash
      );
    },
    calculateSaleTokensReceivedPerBidTokens: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"calculateSaleTokensReceivedPerBidTokens">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"calculateSaleTokensReceivedPerBidTokens">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "calculateSaleTokensReceivedPerBidTokens",
        params,
        getContractByCodeHash
      );
    },
    checkIsWhitelisted: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"checkIsWhitelisted">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"checkIsWhitelisted">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "checkIsWhitelisted",
        params,
        getContractByCodeHash
      );
    },
    setAllFields: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"setAllFields">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"setAllFields">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "setAllFields",
        params,
        getContractByCodeHash
      );
    },
    accountExists: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"accountExists">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"accountExists">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "accountExists",
        params,
        getContractByCodeHash
      );
    },
    getSubContractId: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"getSubContractId">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"getSubContractId">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSubContractId",
        params,
        getContractByCodeHash
      );
    },
    claim: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"claim">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"claim">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "claim",
        params,
        getContractByCodeHash
      );
    },
    claimRefund: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"claimRefund">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"claimRefund">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "claimRefund",
        params,
        getContractByCodeHash
      );
    },
    setMerkleRoot: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"setMerkleRoot">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"setMerkleRoot">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "setMerkleRoot",
        params,
        getContractByCodeHash
      );
    },
    setSaleDates: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"setSaleDates">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"setSaleDates">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "setSaleDates",
        params,
        getContractByCodeHash
      );
    },
    isSaleLive: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"isSaleLive">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"isSaleLive">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "isSaleLive",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isSaleFinished: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"isSaleFinished">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"isSaleFinished">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "isSaleFinished",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isSaleSuccess: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"isSaleSuccess">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"isSaleSuccess">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "isSaleSuccess",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isWhitelistSaleLive: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"isWhitelistSaleLive">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"isWhitelistSaleLive">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "isWhitelistSaleLive",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isWhitelistSale: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"isWhitelistSale">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"isWhitelistSale">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "isWhitelistSale",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    isCallerSaleOwner: async (
      params: SaleFlatPriceAlphV3Types.CallMethodParams<"isCallerSaleOwner">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"isCallerSaleOwner">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "isCallerSaleOwner",
        params,
        getContractByCodeHash
      );
    },
    getSaleOwner: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getSaleOwner">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getSaleOwner">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSaleStart: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getSaleStart">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getSaleStart">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleStart",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSaleEnd: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getSaleEnd">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getSaleEnd">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleEnd",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMinRaise: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getMinRaise">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getMinRaise">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getMinRaise",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMaxRaise: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getMaxRaise">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getMaxRaise">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getMaxRaise",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getSaleTokenId: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getSaleTokenId">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getSaleTokenId">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getBidTokenId: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getBidTokenId">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getBidTokenId">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getBidTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getWhitelistSaleStart: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getWhitelistSaleStart">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"getWhitelistSaleStart">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getWhitelistSaleStart",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getWhitelistSaleEnd: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getWhitelistSaleEnd">
    ): Promise<
      SaleFlatPriceAlphV3Types.CallMethodResult<"getWhitelistSaleEnd">
    > => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getWhitelistSaleEnd",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTokensSold: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getTokensSold">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getTokensSold">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getTokensSold",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalRaised: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getTotalRaised">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getTotalRaised">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getTotalRaised",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMerkleRoot: async (
      params?: SaleFlatPriceAlphV3Types.CallMethodParams<"getMerkleRoot">
    ): Promise<SaleFlatPriceAlphV3Types.CallMethodResult<"getMerkleRoot">> => {
      return callMethod(
        SaleFlatPriceAlphV3,
        this,
        "getMerkleRoot",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    buy: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"buy">
    ): Promise<SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"buy">> => {
      return signExecuteMethod(SaleFlatPriceAlphV3, this, "buy", params);
    },
    calculateClaimableAmount: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"calculateClaimableAmount">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"calculateClaimableAmount">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "calculateClaimableAmount",
        params
      );
    },
    calculateSaleTokensReceivedPerBidTokens: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"calculateSaleTokensReceivedPerBidTokens">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"calculateSaleTokensReceivedPerBidTokens">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "calculateSaleTokensReceivedPerBidTokens",
        params
      );
    },
    checkIsWhitelisted: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"checkIsWhitelisted">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"checkIsWhitelisted">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "checkIsWhitelisted",
        params
      );
    },
    setAllFields: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"setAllFields">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"setAllFields">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "setAllFields",
        params
      );
    },
    accountExists: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"accountExists">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"accountExists">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "accountExists",
        params
      );
    },
    getSubContractId: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getSubContractId">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getSubContractId">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSubContractId",
        params
      );
    },
    claim: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"claim">
    ): Promise<SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"claim">> => {
      return signExecuteMethod(SaleFlatPriceAlphV3, this, "claim", params);
    },
    claimRefund: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"claimRefund">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"claimRefund">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "claimRefund",
        params
      );
    },
    setMerkleRoot: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"setMerkleRoot">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"setMerkleRoot">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "setMerkleRoot",
        params
      );
    },
    setSaleDates: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"setSaleDates">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"setSaleDates">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "setSaleDates",
        params
      );
    },
    isSaleLive: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"isSaleLive">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"isSaleLive">
    > => {
      return signExecuteMethod(SaleFlatPriceAlphV3, this, "isSaleLive", params);
    },
    isSaleFinished: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"isSaleFinished">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"isSaleFinished">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "isSaleFinished",
        params
      );
    },
    isSaleSuccess: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"isSaleSuccess">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"isSaleSuccess">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "isSaleSuccess",
        params
      );
    },
    isWhitelistSaleLive: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"isWhitelistSaleLive">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"isWhitelistSaleLive">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "isWhitelistSaleLive",
        params
      );
    },
    isWhitelistSale: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"isWhitelistSale">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"isWhitelistSale">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "isWhitelistSale",
        params
      );
    },
    isCallerSaleOwner: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"isCallerSaleOwner">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"isCallerSaleOwner">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "isCallerSaleOwner",
        params
      );
    },
    getSaleOwner: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getSaleOwner">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getSaleOwner">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleOwner",
        params
      );
    },
    getSaleStart: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getSaleStart">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getSaleStart">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleStart",
        params
      );
    },
    getSaleEnd: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getSaleEnd">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getSaleEnd">
    > => {
      return signExecuteMethod(SaleFlatPriceAlphV3, this, "getSaleEnd", params);
    },
    getMinRaise: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getMinRaise">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getMinRaise">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getMinRaise",
        params
      );
    },
    getMaxRaise: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getMaxRaise">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getMaxRaise">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getMaxRaise",
        params
      );
    },
    getSaleTokenId: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getSaleTokenId">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getSaleTokenId">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getSaleTokenId",
        params
      );
    },
    getBidTokenId: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getBidTokenId">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getBidTokenId">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getBidTokenId",
        params
      );
    },
    getWhitelistSaleStart: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getWhitelistSaleStart">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getWhitelistSaleStart">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getWhitelistSaleStart",
        params
      );
    },
    getWhitelistSaleEnd: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getWhitelistSaleEnd">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getWhitelistSaleEnd">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getWhitelistSaleEnd",
        params
      );
    },
    getTokensSold: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getTokensSold">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getTokensSold">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getTokensSold",
        params
      );
    },
    getTotalRaised: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getTotalRaised">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getTotalRaised">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getTotalRaised",
        params
      );
    },
    getMerkleRoot: async (
      params: SaleFlatPriceAlphV3Types.SignExecuteMethodParams<"getMerkleRoot">
    ): Promise<
      SaleFlatPriceAlphV3Types.SignExecuteMethodResult<"getMerkleRoot">
    > => {
      return signExecuteMethod(
        SaleFlatPriceAlphV3,
        this,
        "getMerkleRoot",
        params
      );
    },
  };

  async multicall<Callss extends SaleFlatPriceAlphV3Types.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<SaleFlatPriceAlphV3Types.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      SaleFlatPriceAlphV3,
      this,
      callss,
      getContractByCodeHash
    )) as SaleFlatPriceAlphV3Types.MulticallReturnType<Callss>;
  }
}
