/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as SaleManagerV3x1ContractJson } from "../launch_sale_v3/SaleManagerV3x1.ral.json";
import { getContractByCodeHash } from "./contracts";
import { ListingRecord, AllStructs } from "./types";
import { RalphMap } from "@alephium/web3";

// Custom types for the contract
export namespace SaleManagerV3x1Types {
  export type Fields = {
    rewardDistributor: HexString;
    alphTokenId: HexString;
    listingFeeAmount: bigint;
    upgradeDelay: bigint;
    saleFlatPriceAlphTemplateId: HexString;
    accountTemplateId: HexString;
    saleCounter: bigint;
    listingCounter: bigint;
    listingsReviewer: Address;
    owner: Address;
    newOwner: Address;
    upgradeCommenced: bigint;
    newCode: HexString;
    newImmFieldsEncoded: HexString;
    newMutFieldsEncoded: HexString;
  };

  export type State = ContractState<Fields>;

  export type ChangeOwnerCommenceEvent = ContractEvent<{
    owner: Address;
    changeOwner: Address;
  }>;
  export type ChangeOwnerApplyEvent = ContractEvent<{
    owner: Address;
    changeOwner: Address;
  }>;
  export type MigrateCommenceEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
  }>;
  export type MigrateApplyEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
  }>;
  export type MigrateWithFieldsCommenceEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
    changeImmFieldsEncoded: HexString;
    changeMutFieldsEncoded: HexString;
  }>;
  export type MigrateWithFieldsApplyEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
    changeImmFieldsEncoded: HexString;
    changeMutFieldsEncoded: HexString;
  }>;
  export type CreateSaleFlatPriceAlphEvent = ContractEvent<{
    account: Address;
    saleIndex: bigint;
    contractId: HexString;
  }>;
  export type CreateListingRecordEvent = ContractEvent<{
    caller: Address;
    listingIndex: bigint;
  }>;
  export type UpdateListingContractIdEvent = ContractEvent<{
    caller: Address;
    listingIndex: bigint;
    contractId: HexString;
  }>;
  export type UpdateListingStatusEvent = ContractEvent<{
    caller: Address;
    listingIndex: bigint;
    newStatus: HexString;
  }>;
  export type UpdateListingReviewerEvent = ContractEvent<{
    caller: Address;
    newListingsReviewer: Address;
  }>;

  export interface CallMethodTable {
    changeOwner: {
      params: CallContractParams<{ changeOwner: Address }>;
      result: CallContractResult<null>;
    };
    migrate: {
      params: CallContractParams<{ changeCode: HexString }>;
      result: CallContractResult<null>;
    };
    migrateWithFields: {
      params: CallContractParams<{
        changeCode: HexString;
        changeImmFieldsEncoded: HexString;
        changeMutFieldsEncoded: HexString;
      }>;
      result: CallContractResult<null>;
    };
    changeOwnerApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    migrateApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    migrateWithFieldsApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    resetUpgrade: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getUpgradeDelay: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getNewOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getUpgradeCommenced: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getNewCode: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNewImmFieldsEncoded: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNewMutFieldsEncoded: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    createListingRecord: {
      params: CallContractParams<{ amountAlph: bigint }>;
      result: CallContractResult<null>;
    };
    updateListingStatus: {
      params: CallContractParams<{
        listingRecordIndex: bigint;
        newStatus: HexString;
      }>;
      result: CallContractResult<null>;
    };
    getListing: {
      params: CallContractParams<{ listingRecordIndex: bigint }>;
      result: CallContractResult<ListingRecord>;
    };
    changeListingReviewer: {
      params: CallContractParams<{ newListingsReviewer: Address }>;
      result: CallContractResult<null>;
    };
    createSaleFlatPriceAlph: {
      params: CallContractParams<{
        listingRecordIndex: bigint;
        tokenPrice: bigint;
        publicSaleMaxBid: bigint;
        upfrontRelease: bigint;
        vestingEnd: bigint;
        cliffEnd: bigint;
        saleStart: bigint;
        saleEnd: bigint;
        minRaise: bigint;
        maxRaise: bigint;
        saleTokenId: HexString;
        saleTokenTotalAmount: bigint;
        whitelistSaleEnd: bigint;
        merkleRoot: HexString;
      }>;
      result: CallContractResult<null>;
    };
    calculateListingFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> =
    Callss["length"] extends 1
      ? MultiCallResults<Callss[0]>
      : { [index in keyof Callss]: MultiCallResults<Callss[index]> };

  export interface SignExecuteMethodTable {
    changeOwner: {
      params: SignExecuteContractMethodParams<{ changeOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    migrate: {
      params: SignExecuteContractMethodParams<{ changeCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFields: {
      params: SignExecuteContractMethodParams<{
        changeCode: HexString;
        changeImmFieldsEncoded: HexString;
        changeMutFieldsEncoded: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwnerApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrateApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFieldsApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    resetUpgrade: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUpgradeDelay: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUpgradeCommenced: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewCode: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewImmFieldsEncoded: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewMutFieldsEncoded: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    createListingRecord: {
      params: SignExecuteContractMethodParams<{ amountAlph: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    updateListingStatus: {
      params: SignExecuteContractMethodParams<{
        listingRecordIndex: bigint;
        newStatus: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    getListing: {
      params: SignExecuteContractMethodParams<{ listingRecordIndex: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    changeListingReviewer: {
      params: SignExecuteContractMethodParams<{ newListingsReviewer: Address }>;
      result: SignExecuteScriptTxResult;
    };
    createSaleFlatPriceAlph: {
      params: SignExecuteContractMethodParams<{
        listingRecordIndex: bigint;
        tokenPrice: bigint;
        publicSaleMaxBid: bigint;
        upfrontRelease: bigint;
        vestingEnd: bigint;
        cliffEnd: bigint;
        saleStart: bigint;
        saleEnd: bigint;
        minRaise: bigint;
        maxRaise: bigint;
        saleTokenId: HexString;
        saleTokenTotalAmount: bigint;
        whitelistSaleEnd: bigint;
        merkleRoot: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    calculateListingFee: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  SaleManagerV3x1Instance,
  SaleManagerV3x1Types.Fields
> {
  encodeFields(fields: SaleManagerV3x1Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      AllStructs
    );
  }

  eventIndex = {
    ChangeOwnerCommence: 0,
    ChangeOwnerApply: 1,
    MigrateCommence: 2,
    MigrateApply: 3,
    MigrateWithFieldsCommence: 4,
    MigrateWithFieldsApply: 5,
    CreateSaleFlatPriceAlph: 6,
    CreateListingRecord: 7,
    UpdateListingContractId: 8,
    UpdateListingStatus: 9,
    UpdateListingReviewer: 10,
  };
  consts = {
    UpgradeErrorCodes: {
      Forbidden: BigInt("13000"),
      UpgradePending: BigInt("13001"),
      UpgradeNotPending: BigInt("13002"),
      UpgradeDelayNotExpired: BigInt("13003"),
      MigrateNotPending: BigInt("13004"),
      MigrateWithFieldsNotPending: BigInt("13005"),
      ChangeOwnerNotPending: BigInt("13006"),
    },
    ErrorCodes: {
      ListingFeeMustBePaid: BigInt("501"),
      PriceLargerThanMax: BigInt("502"),
      PriceSmallerThanMin: BigInt("503"),
      RaiseLargerThanMax: BigInt("504"),
      RaiseSmallerThanMin: BigInt("505"),
      SaleStartMustBeInFuture: BigInt("506"),
      SaleEndMustBeAfterSaleStart: BigInt("507"),
      SaleAmountSmallerThanMin: BigInt("508"),
      SaleAmountLargerThanMax: BigInt("509"),
      WLSaleEndMustBeWithinSaleDatesAndAfterWLSaleStart: BigInt("511"),
      WLSaleInvalidMerkleRootSize: BigInt("514"),
      WLSaleMerkleRootMustNotBeZeroes: BigInt("515"),
      CliffEndOutOfRange: BigInt("517"),
      UpfrontReleaseOutOfRange: BigInt("518"),
      VestingEndOutOfRange: BigInt("519"),
      PublicSaleMaxBidMinimum: BigInt("520"),
      Unauthorized: BigInt("521"),
      ListingDoesntExist: BigInt("522"),
    },
  };

  at(address: string): SaleManagerV3x1Instance {
    return new SaleManagerV3x1Instance(address);
  }

  tests = {
    changeOwner: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { changeOwner: Address },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    migrate: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { changeCode: HexString },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "migrate", params, getContractByCodeHash);
    },
    migrateWithFields: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        {
          changeCode: HexString;
          changeImmFieldsEncoded: HexString;
          changeMutFieldsEncoded: HexString;
        },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
    changeOwnerApply: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "changeOwnerApply",
        params,
        getContractByCodeHash
      );
    },
    migrateApply: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "migrateApply", params, getContractByCodeHash);
    },
    migrateWithFieldsApply: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "migrateWithFieldsApply",
        params,
        getContractByCodeHash
      );
    },
    resetUpgrade: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "resetUpgrade", params, getContractByCodeHash);
    },
    getUpgradeDelay: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<bigint, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "getUpgradeDelay", params, getContractByCodeHash);
    },
    getOwner: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<Address, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "getOwner", params, getContractByCodeHash);
    },
    getNewOwner: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<Address, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "getNewOwner", params, getContractByCodeHash);
    },
    getUpgradeCommenced: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<bigint, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "getUpgradeCommenced",
        params,
        getContractByCodeHash
      );
    },
    getNewCode: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<HexString, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "getNewCode", params, getContractByCodeHash);
    },
    getNewImmFieldsEncoded: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<HexString, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "getNewImmFieldsEncoded",
        params,
        getContractByCodeHash
      );
    },
    getNewMutFieldsEncoded: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<HexString, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "getNewMutFieldsEncoded",
        params,
        getContractByCodeHash
      );
    },
    resetFields: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "resetFields", params, getContractByCodeHash);
    },
    assertOnlyOwner: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { caller: Address },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "assertOnlyOwner", params, getContractByCodeHash);
    },
    assertUpgradeNotPending: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "assertUpgradeNotPending",
        params,
        getContractByCodeHash
      );
    },
    assertUpgradeDelayElapsed: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "assertUpgradeDelayElapsed",
        params,
        getContractByCodeHash
      );
    },
    createListingRecord: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { amountAlph: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "createListingRecord",
        params,
        getContractByCodeHash
      );
    },
    updateListingStatus: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { listingRecordIndex: bigint; newStatus: HexString },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "updateListingStatus",
        params,
        getContractByCodeHash
      );
    },
    getListing: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { listingRecordIndex: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<
        ListingRecord,
        { listings?: Map<bigint, ListingRecord> }
      >
    > => {
      return testMethod(this, "getListing", params, getContractByCodeHash);
    },
    changeListingReviewer: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { newListingsReviewer: Address },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "changeListingReviewer",
        params,
        getContractByCodeHash
      );
    },
    createSaleFlatPriceAlph: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        {
          listingRecordIndex: bigint;
          tokenPrice: bigint;
          publicSaleMaxBid: bigint;
          upfrontRelease: bigint;
          vestingEnd: bigint;
          cliffEnd: bigint;
          saleStart: bigint;
          saleEnd: bigint;
          minRaise: bigint;
          maxRaise: bigint;
          saleTokenId: HexString;
          saleTokenTotalAmount: bigint;
          whitelistSaleEnd: bigint;
          merkleRoot: HexString;
        },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "createSaleFlatPriceAlph",
        params,
        getContractByCodeHash
      );
    },
    calculateListingFee: async (
      params: Omit<
        TestContractParams<
          SaleManagerV3x1Types.Fields,
          never,
          { listings?: Map<bigint, ListingRecord> }
        >,
        "testArgs"
      >
    ): Promise<
      TestContractResult<bigint, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "calculateListingFee",
        params,
        getContractByCodeHash
      );
    },
    assertPriceInRange: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { tokenPrice: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "assertPriceInRange",
        params,
        getContractByCodeHash
      );
    },
    assertAlphAmountInRange: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { alphAmount: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "assertAlphAmountInRange",
        params,
        getContractByCodeHash
      );
    },
    assertSaleAmountInRange: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { saleAmount: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "assertSaleAmountInRange",
        params,
        getContractByCodeHash
      );
    },
    assertSaleDates: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { saleStart: bigint; saleEnd: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(this, "assertSaleDates", params, getContractByCodeHash);
    },
    assertListingFeePaid: async (
      params: TestContractParams<
        SaleManagerV3x1Types.Fields,
        { amountAlph: bigint },
        { listings?: Map<bigint, ListingRecord> }
      >
    ): Promise<
      TestContractResult<null, { listings?: Map<bigint, ListingRecord> }>
    > => {
      return testMethod(
        this,
        "assertListingFeePaid",
        params,
        getContractByCodeHash
      );
    },
  };
}

// Use this object to test and deploy the contract
export const SaleManagerV3x1 = new Factory(
  Contract.fromJson(
    SaleManagerV3x1ContractJson,
    "=78-2+3e=2+d1431=1-1=2-3=1-6+d=3-1+9=2-2+bf=2-1=1+b=3-1+6=3-1+2=2+39=1-1+55f=927-1+a=136+7a7e0214696e73657274206174206d617020706174683a2000=1636",
    "746939724f7640ecec7f5e555b322e9e2277bfddfe5d44ac31814c5393a3964a",
    AllStructs
  )
);

// Use this class to interact with the blockchain
export class SaleManagerV3x1Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  maps = {
    listings: new RalphMap<bigint, ListingRecord>(
      SaleManagerV3x1.contract,
      this.contractId,
      "listings"
    ),
  };

  async fetchState(): Promise<SaleManagerV3x1Types.State> {
    return fetchContractState(SaleManagerV3x1, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeChangeOwnerCommenceEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.ChangeOwnerCommenceEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "ChangeOwnerCommence",
      fromCount
    );
  }

  subscribeChangeOwnerApplyEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.ChangeOwnerApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "ChangeOwnerApply",
      fromCount
    );
  }

  subscribeMigrateCommenceEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.MigrateCommenceEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "MigrateCommence",
      fromCount
    );
  }

  subscribeMigrateApplyEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.MigrateApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "MigrateApply",
      fromCount
    );
  }

  subscribeMigrateWithFieldsCommenceEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.MigrateWithFieldsCommenceEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "MigrateWithFieldsCommence",
      fromCount
    );
  }

  subscribeMigrateWithFieldsApplyEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.MigrateWithFieldsApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "MigrateWithFieldsApply",
      fromCount
    );
  }

  subscribeCreateSaleFlatPriceAlphEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.CreateSaleFlatPriceAlphEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "CreateSaleFlatPriceAlph",
      fromCount
    );
  }

  subscribeCreateListingRecordEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.CreateListingRecordEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "CreateListingRecord",
      fromCount
    );
  }

  subscribeUpdateListingContractIdEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.UpdateListingContractIdEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "UpdateListingContractId",
      fromCount
    );
  }

  subscribeUpdateListingStatusEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.UpdateListingStatusEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "UpdateListingStatus",
      fromCount
    );
  }

  subscribeUpdateListingReviewerEvent(
    options: EventSubscribeOptions<SaleManagerV3x1Types.UpdateListingReviewerEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      SaleManagerV3x1.contract,
      this,
      options,
      "UpdateListingReviewer",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | SaleManagerV3x1Types.ChangeOwnerCommenceEvent
      | SaleManagerV3x1Types.ChangeOwnerApplyEvent
      | SaleManagerV3x1Types.MigrateCommenceEvent
      | SaleManagerV3x1Types.MigrateApplyEvent
      | SaleManagerV3x1Types.MigrateWithFieldsCommenceEvent
      | SaleManagerV3x1Types.MigrateWithFieldsApplyEvent
      | SaleManagerV3x1Types.CreateSaleFlatPriceAlphEvent
      | SaleManagerV3x1Types.CreateListingRecordEvent
      | SaleManagerV3x1Types.UpdateListingContractIdEvent
      | SaleManagerV3x1Types.UpdateListingStatusEvent
      | SaleManagerV3x1Types.UpdateListingReviewerEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      SaleManagerV3x1.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    changeOwner: async (
      params: SaleManagerV3x1Types.CallMethodParams<"changeOwner">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"changeOwner">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    migrate: async (
      params: SaleManagerV3x1Types.CallMethodParams<"migrate">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"migrate">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "migrate",
        params,
        getContractByCodeHash
      );
    },
    migrateWithFields: async (
      params: SaleManagerV3x1Types.CallMethodParams<"migrateWithFields">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"migrateWithFields">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
    changeOwnerApply: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"changeOwnerApply">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"changeOwnerApply">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "changeOwnerApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrateApply: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"migrateApply">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"migrateApply">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "migrateApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrateWithFieldsApply: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"migrateWithFieldsApply">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"migrateWithFieldsApply">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "migrateWithFieldsApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    resetUpgrade: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"resetUpgrade">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"resetUpgrade">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "resetUpgrade",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUpgradeDelay: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getUpgradeDelay">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"getUpgradeDelay">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getUpgradeDelay",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOwner: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getOwner">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"getOwner">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewOwner: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getNewOwner">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"getNewOwner">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getNewOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUpgradeCommenced: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getUpgradeCommenced">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"getUpgradeCommenced">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getUpgradeCommenced",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewCode: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getNewCode">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"getNewCode">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getNewCode",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewImmFieldsEncoded: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getNewImmFieldsEncoded">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"getNewImmFieldsEncoded">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getNewImmFieldsEncoded",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewMutFieldsEncoded: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"getNewMutFieldsEncoded">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"getNewMutFieldsEncoded">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getNewMutFieldsEncoded",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    createListingRecord: async (
      params: SaleManagerV3x1Types.CallMethodParams<"createListingRecord">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"createListingRecord">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "createListingRecord",
        params,
        getContractByCodeHash
      );
    },
    updateListingStatus: async (
      params: SaleManagerV3x1Types.CallMethodParams<"updateListingStatus">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"updateListingStatus">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "updateListingStatus",
        params,
        getContractByCodeHash
      );
    },
    getListing: async (
      params: SaleManagerV3x1Types.CallMethodParams<"getListing">
    ): Promise<SaleManagerV3x1Types.CallMethodResult<"getListing">> => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "getListing",
        params,
        getContractByCodeHash
      );
    },
    changeListingReviewer: async (
      params: SaleManagerV3x1Types.CallMethodParams<"changeListingReviewer">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"changeListingReviewer">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "changeListingReviewer",
        params,
        getContractByCodeHash
      );
    },
    createSaleFlatPriceAlph: async (
      params: SaleManagerV3x1Types.CallMethodParams<"createSaleFlatPriceAlph">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"createSaleFlatPriceAlph">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "createSaleFlatPriceAlph",
        params,
        getContractByCodeHash
      );
    },
    calculateListingFee: async (
      params?: SaleManagerV3x1Types.CallMethodParams<"calculateListingFee">
    ): Promise<
      SaleManagerV3x1Types.CallMethodResult<"calculateListingFee">
    > => {
      return callMethod(
        SaleManagerV3x1,
        this,
        "calculateListingFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    changeOwner: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"changeOwner">
    ): Promise<SaleManagerV3x1Types.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(SaleManagerV3x1, this, "changeOwner", params);
    },
    migrate: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"migrate">
    ): Promise<SaleManagerV3x1Types.SignExecuteMethodResult<"migrate">> => {
      return signExecuteMethod(SaleManagerV3x1, this, "migrate", params);
    },
    migrateWithFields: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"migrateWithFields">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"migrateWithFields">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "migrateWithFields",
        params
      );
    },
    changeOwnerApply: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"changeOwnerApply">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"changeOwnerApply">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "changeOwnerApply",
        params
      );
    },
    migrateApply: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"migrateApply">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"migrateApply">
    > => {
      return signExecuteMethod(SaleManagerV3x1, this, "migrateApply", params);
    },
    migrateWithFieldsApply: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"migrateWithFieldsApply">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"migrateWithFieldsApply">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "migrateWithFieldsApply",
        params
      );
    },
    resetUpgrade: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"resetUpgrade">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"resetUpgrade">
    > => {
      return signExecuteMethod(SaleManagerV3x1, this, "resetUpgrade", params);
    },
    getUpgradeDelay: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getUpgradeDelay">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"getUpgradeDelay">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "getUpgradeDelay",
        params
      );
    },
    getOwner: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getOwner">
    ): Promise<SaleManagerV3x1Types.SignExecuteMethodResult<"getOwner">> => {
      return signExecuteMethod(SaleManagerV3x1, this, "getOwner", params);
    },
    getNewOwner: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getNewOwner">
    ): Promise<SaleManagerV3x1Types.SignExecuteMethodResult<"getNewOwner">> => {
      return signExecuteMethod(SaleManagerV3x1, this, "getNewOwner", params);
    },
    getUpgradeCommenced: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getUpgradeCommenced">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"getUpgradeCommenced">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "getUpgradeCommenced",
        params
      );
    },
    getNewCode: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getNewCode">
    ): Promise<SaleManagerV3x1Types.SignExecuteMethodResult<"getNewCode">> => {
      return signExecuteMethod(SaleManagerV3x1, this, "getNewCode", params);
    },
    getNewImmFieldsEncoded: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getNewImmFieldsEncoded">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"getNewImmFieldsEncoded">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "getNewImmFieldsEncoded",
        params
      );
    },
    getNewMutFieldsEncoded: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getNewMutFieldsEncoded">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"getNewMutFieldsEncoded">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "getNewMutFieldsEncoded",
        params
      );
    },
    createListingRecord: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"createListingRecord">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"createListingRecord">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "createListingRecord",
        params
      );
    },
    updateListingStatus: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"updateListingStatus">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"updateListingStatus">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "updateListingStatus",
        params
      );
    },
    getListing: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"getListing">
    ): Promise<SaleManagerV3x1Types.SignExecuteMethodResult<"getListing">> => {
      return signExecuteMethod(SaleManagerV3x1, this, "getListing", params);
    },
    changeListingReviewer: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"changeListingReviewer">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"changeListingReviewer">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "changeListingReviewer",
        params
      );
    },
    createSaleFlatPriceAlph: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"createSaleFlatPriceAlph">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"createSaleFlatPriceAlph">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "createSaleFlatPriceAlph",
        params
      );
    },
    calculateListingFee: async (
      params: SaleManagerV3x1Types.SignExecuteMethodParams<"calculateListingFee">
    ): Promise<
      SaleManagerV3x1Types.SignExecuteMethodResult<"calculateListingFee">
    > => {
      return signExecuteMethod(
        SaleManagerV3x1,
        this,
        "calculateListingFee",
        params
      );
    },
  };

  async multicall<Callss extends SaleManagerV3x1Types.MultiCallParams[]>(
    ...callss: Callss
  ): Promise<SaleManagerV3x1Types.MulticallReturnType<Callss>> {
    return (await multicallMethods(
      SaleManagerV3x1,
      this,
      callss,
      getContractByCodeHash
    )) as SaleManagerV3x1Types.MulticallReturnType<Callss>;
  }
}
