/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
} from "@alephium/web3";
import { default as TestUpgradableContractJson } from "../lib/dummy/TestUpgradable.ral.json";
import { getContractByCodeHash } from "./contracts";

// Custom types for the contract
export namespace TestUpgradableTypes {
  export type Fields = {
    immValue: bigint;
    upgradeDelay: bigint;
    mutValue: bigint;
    owner: Address;
    newOwner: Address;
    upgradeCommenced: bigint;
    newCode: HexString;
    newImmFieldsEncoded: HexString;
    newMutFieldsEncoded: HexString;
  };

  export type State = ContractState<Fields>;

  export type ChangeOwnerCommenceEvent = ContractEvent<{
    owner: Address;
    changeOwner: Address;
  }>;
  export type ChangeOwnerApplyEvent = ContractEvent<{
    owner: Address;
    changeOwner: Address;
  }>;
  export type MigrateCommenceEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
  }>;
  export type MigrateApplyEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
  }>;
  export type MigrateWithFieldsCommenceEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
    changeImmFieldsEncoded: HexString;
    changeMutFieldsEncoded: HexString;
  }>;
  export type MigrateWithFieldsApplyEvent = ContractEvent<{
    owner: Address;
    changeCode: HexString;
    changeImmFieldsEncoded: HexString;
    changeMutFieldsEncoded: HexString;
  }>;

  export interface CallMethodTable {
    changeOwner: {
      params: CallContractParams<{ changeOwner: Address }>;
      result: CallContractResult<null>;
    };
    migrate: {
      params: CallContractParams<{ changeCode: HexString }>;
      result: CallContractResult<null>;
    };
    migrateWithFields: {
      params: CallContractParams<{
        changeCode: HexString;
        changeImmFieldsEncoded: HexString;
        changeMutFieldsEncoded: HexString;
      }>;
      result: CallContractResult<null>;
    };
    changeOwnerApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    migrateApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    migrateWithFieldsApply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    resetUpgrade: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    getUpgradeDelay: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getNewOwner: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    getUpgradeCommenced: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getNewCode: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNewImmFieldsEncoded: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getNewMutFieldsEncoded: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getImmValue: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getMutValue: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    setMutValue: {
      params: CallContractParams<{ newMutValue: bigint }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };

  export interface SignExecuteMethodTable {
    changeOwner: {
      params: SignExecuteContractMethodParams<{ changeOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    migrate: {
      params: SignExecuteContractMethodParams<{ changeCode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFields: {
      params: SignExecuteContractMethodParams<{
        changeCode: HexString;
        changeImmFieldsEncoded: HexString;
        changeMutFieldsEncoded: HexString;
      }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwnerApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrateApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    migrateWithFieldsApply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    resetUpgrade: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUpgradeDelay: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewOwner: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getUpgradeCommenced: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewCode: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewImmFieldsEncoded: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getNewMutFieldsEncoded: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getImmValue: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getMutValue: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setMutValue: {
      params: SignExecuteContractMethodParams<{ newMutValue: bigint }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  TestUpgradableInstance,
  TestUpgradableTypes.Fields
> {
  encodeFields(fields: TestUpgradableTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  getInitialFieldsWithDefaultValues() {
    return this.contract.getInitialFieldsWithDefaultValues() as TestUpgradableTypes.Fields;
  }

  eventIndex = {
    ChangeOwnerCommence: 0,
    ChangeOwnerApply: 1,
    MigrateCommence: 2,
    MigrateApply: 3,
    MigrateWithFieldsCommence: 4,
    MigrateWithFieldsApply: 5,
  };
  consts = {
    UpgradeErrorCodes: {
      Forbidden: BigInt(13000),
      UpgradePending: BigInt(13001),
      UpgradeNotPending: BigInt(13002),
      UpgradeDelayNotExpired: BigInt(13003),
      MigrateNotPending: BigInt(13004),
      MigrateWithFieldsNotPending: BigInt(13005),
      ChangeOwnerNotPending: BigInt(13006),
    },
  };

  at(address: string): TestUpgradableInstance {
    return new TestUpgradableInstance(address);
  }

  tests = {
    changeOwner: async (
      params: TestContractParamsWithoutMaps<
        TestUpgradableTypes.Fields,
        { changeOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    migrate: async (
      params: TestContractParamsWithoutMaps<
        TestUpgradableTypes.Fields,
        { changeCode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "migrate", params, getContractByCodeHash);
    },
    migrateWithFields: async (
      params: TestContractParamsWithoutMaps<
        TestUpgradableTypes.Fields,
        {
          changeCode: HexString;
          changeImmFieldsEncoded: HexString;
          changeMutFieldsEncoded: HexString;
        }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
    changeOwnerApply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "changeOwnerApply",
        params,
        getContractByCodeHash
      );
    },
    migrateApply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "migrateApply", params, getContractByCodeHash);
    },
    migrateWithFieldsApply: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "migrateWithFieldsApply",
        params,
        getContractByCodeHash
      );
    },
    resetUpgrade: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "resetUpgrade", params, getContractByCodeHash);
    },
    getUpgradeDelay: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getUpgradeDelay", params, getContractByCodeHash);
    },
    getOwner: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getOwner", params, getContractByCodeHash);
    },
    getNewOwner: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getNewOwner", params, getContractByCodeHash);
    },
    getUpgradeCommenced: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getUpgradeCommenced",
        params,
        getContractByCodeHash
      );
    },
    getNewCode: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getNewCode", params, getContractByCodeHash);
    },
    getNewImmFieldsEncoded: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getNewImmFieldsEncoded",
        params,
        getContractByCodeHash
      );
    },
    getNewMutFieldsEncoded: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getNewMutFieldsEncoded",
        params,
        getContractByCodeHash
      );
    },
    resetFields: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "resetFields", params, getContractByCodeHash);
    },
    assertOnlyOwner: async (
      params: TestContractParamsWithoutMaps<
        TestUpgradableTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "assertOnlyOwner", params, getContractByCodeHash);
    },
    assertUpgradeNotPending: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertUpgradeNotPending",
        params,
        getContractByCodeHash
      );
    },
    assertUpgradeDelayElapsed: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "assertUpgradeDelayElapsed",
        params,
        getContractByCodeHash
      );
    },
    getImmValue: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getImmValue", params, getContractByCodeHash);
    },
    getMutValue: async (
      params: Omit<
        TestContractParamsWithoutMaps<TestUpgradableTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getMutValue", params, getContractByCodeHash);
    },
    setMutValue: async (
      params: TestContractParamsWithoutMaps<
        TestUpgradableTypes.Fields,
        { newMutValue: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setMutValue", params, getContractByCodeHash);
    },
  };
}

// Use this object to test and deploy the contract
export const TestUpgradable = new Factory(
  Contract.fromJson(
    TestUpgradableContractJson,
    "",
    "9bf3009274456447b20ea932f5eb747e867b0977f8fb910075616925a3fb4c7e",
    []
  )
);

// Use this class to interact with the blockchain
export class TestUpgradableInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<TestUpgradableTypes.State> {
    return fetchContractState(TestUpgradable, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeChangeOwnerCommenceEvent(
    options: EventSubscribeOptions<TestUpgradableTypes.ChangeOwnerCommenceEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TestUpgradable.contract,
      this,
      options,
      "ChangeOwnerCommence",
      fromCount
    );
  }

  subscribeChangeOwnerApplyEvent(
    options: EventSubscribeOptions<TestUpgradableTypes.ChangeOwnerApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TestUpgradable.contract,
      this,
      options,
      "ChangeOwnerApply",
      fromCount
    );
  }

  subscribeMigrateCommenceEvent(
    options: EventSubscribeOptions<TestUpgradableTypes.MigrateCommenceEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TestUpgradable.contract,
      this,
      options,
      "MigrateCommence",
      fromCount
    );
  }

  subscribeMigrateApplyEvent(
    options: EventSubscribeOptions<TestUpgradableTypes.MigrateApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TestUpgradable.contract,
      this,
      options,
      "MigrateApply",
      fromCount
    );
  }

  subscribeMigrateWithFieldsCommenceEvent(
    options: EventSubscribeOptions<TestUpgradableTypes.MigrateWithFieldsCommenceEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TestUpgradable.contract,
      this,
      options,
      "MigrateWithFieldsCommence",
      fromCount
    );
  }

  subscribeMigrateWithFieldsApplyEvent(
    options: EventSubscribeOptions<TestUpgradableTypes.MigrateWithFieldsApplyEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      TestUpgradable.contract,
      this,
      options,
      "MigrateWithFieldsApply",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | TestUpgradableTypes.ChangeOwnerCommenceEvent
      | TestUpgradableTypes.ChangeOwnerApplyEvent
      | TestUpgradableTypes.MigrateCommenceEvent
      | TestUpgradableTypes.MigrateApplyEvent
      | TestUpgradableTypes.MigrateWithFieldsCommenceEvent
      | TestUpgradableTypes.MigrateWithFieldsApplyEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      TestUpgradable.contract,
      this,
      options,
      fromCount
    );
  }

  methods = {
    changeOwner: async (
      params: TestUpgradableTypes.CallMethodParams<"changeOwner">
    ): Promise<TestUpgradableTypes.CallMethodResult<"changeOwner">> => {
      return callMethod(
        TestUpgradable,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    migrate: async (
      params: TestUpgradableTypes.CallMethodParams<"migrate">
    ): Promise<TestUpgradableTypes.CallMethodResult<"migrate">> => {
      return callMethod(
        TestUpgradable,
        this,
        "migrate",
        params,
        getContractByCodeHash
      );
    },
    migrateWithFields: async (
      params: TestUpgradableTypes.CallMethodParams<"migrateWithFields">
    ): Promise<TestUpgradableTypes.CallMethodResult<"migrateWithFields">> => {
      return callMethod(
        TestUpgradable,
        this,
        "migrateWithFields",
        params,
        getContractByCodeHash
      );
    },
    changeOwnerApply: async (
      params?: TestUpgradableTypes.CallMethodParams<"changeOwnerApply">
    ): Promise<TestUpgradableTypes.CallMethodResult<"changeOwnerApply">> => {
      return callMethod(
        TestUpgradable,
        this,
        "changeOwnerApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrateApply: async (
      params?: TestUpgradableTypes.CallMethodParams<"migrateApply">
    ): Promise<TestUpgradableTypes.CallMethodResult<"migrateApply">> => {
      return callMethod(
        TestUpgradable,
        this,
        "migrateApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    migrateWithFieldsApply: async (
      params?: TestUpgradableTypes.CallMethodParams<"migrateWithFieldsApply">
    ): Promise<
      TestUpgradableTypes.CallMethodResult<"migrateWithFieldsApply">
    > => {
      return callMethod(
        TestUpgradable,
        this,
        "migrateWithFieldsApply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    resetUpgrade: async (
      params?: TestUpgradableTypes.CallMethodParams<"resetUpgrade">
    ): Promise<TestUpgradableTypes.CallMethodResult<"resetUpgrade">> => {
      return callMethod(
        TestUpgradable,
        this,
        "resetUpgrade",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUpgradeDelay: async (
      params?: TestUpgradableTypes.CallMethodParams<"getUpgradeDelay">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getUpgradeDelay">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getUpgradeDelay",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getOwner: async (
      params?: TestUpgradableTypes.CallMethodParams<"getOwner">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getOwner">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewOwner: async (
      params?: TestUpgradableTypes.CallMethodParams<"getNewOwner">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getNewOwner">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getNewOwner",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getUpgradeCommenced: async (
      params?: TestUpgradableTypes.CallMethodParams<"getUpgradeCommenced">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getUpgradeCommenced">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getUpgradeCommenced",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewCode: async (
      params?: TestUpgradableTypes.CallMethodParams<"getNewCode">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getNewCode">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getNewCode",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewImmFieldsEncoded: async (
      params?: TestUpgradableTypes.CallMethodParams<"getNewImmFieldsEncoded">
    ): Promise<
      TestUpgradableTypes.CallMethodResult<"getNewImmFieldsEncoded">
    > => {
      return callMethod(
        TestUpgradable,
        this,
        "getNewImmFieldsEncoded",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getNewMutFieldsEncoded: async (
      params?: TestUpgradableTypes.CallMethodParams<"getNewMutFieldsEncoded">
    ): Promise<
      TestUpgradableTypes.CallMethodResult<"getNewMutFieldsEncoded">
    > => {
      return callMethod(
        TestUpgradable,
        this,
        "getNewMutFieldsEncoded",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getImmValue: async (
      params?: TestUpgradableTypes.CallMethodParams<"getImmValue">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getImmValue">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getImmValue",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getMutValue: async (
      params?: TestUpgradableTypes.CallMethodParams<"getMutValue">
    ): Promise<TestUpgradableTypes.CallMethodResult<"getMutValue">> => {
      return callMethod(
        TestUpgradable,
        this,
        "getMutValue",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setMutValue: async (
      params: TestUpgradableTypes.CallMethodParams<"setMutValue">
    ): Promise<TestUpgradableTypes.CallMethodResult<"setMutValue">> => {
      return callMethod(
        TestUpgradable,
        this,
        "setMutValue",
        params,
        getContractByCodeHash
      );
    },
  };

  view = this.methods;

  transact = {
    changeOwner: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"changeOwner">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(TestUpgradable, this, "changeOwner", params);
    },
    migrate: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"migrate">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"migrate">> => {
      return signExecuteMethod(TestUpgradable, this, "migrate", params);
    },
    migrateWithFields: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"migrateWithFields">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"migrateWithFields">
    > => {
      return signExecuteMethod(
        TestUpgradable,
        this,
        "migrateWithFields",
        params
      );
    },
    changeOwnerApply: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"changeOwnerApply">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"changeOwnerApply">
    > => {
      return signExecuteMethod(
        TestUpgradable,
        this,
        "changeOwnerApply",
        params
      );
    },
    migrateApply: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"migrateApply">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"migrateApply">> => {
      return signExecuteMethod(TestUpgradable, this, "migrateApply", params);
    },
    migrateWithFieldsApply: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"migrateWithFieldsApply">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"migrateWithFieldsApply">
    > => {
      return signExecuteMethod(
        TestUpgradable,
        this,
        "migrateWithFieldsApply",
        params
      );
    },
    resetUpgrade: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"resetUpgrade">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"resetUpgrade">> => {
      return signExecuteMethod(TestUpgradable, this, "resetUpgrade", params);
    },
    getUpgradeDelay: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getUpgradeDelay">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"getUpgradeDelay">
    > => {
      return signExecuteMethod(TestUpgradable, this, "getUpgradeDelay", params);
    },
    getOwner: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getOwner">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"getOwner">> => {
      return signExecuteMethod(TestUpgradable, this, "getOwner", params);
    },
    getNewOwner: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getNewOwner">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"getNewOwner">> => {
      return signExecuteMethod(TestUpgradable, this, "getNewOwner", params);
    },
    getUpgradeCommenced: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getUpgradeCommenced">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"getUpgradeCommenced">
    > => {
      return signExecuteMethod(
        TestUpgradable,
        this,
        "getUpgradeCommenced",
        params
      );
    },
    getNewCode: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getNewCode">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"getNewCode">> => {
      return signExecuteMethod(TestUpgradable, this, "getNewCode", params);
    },
    getNewImmFieldsEncoded: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getNewImmFieldsEncoded">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"getNewImmFieldsEncoded">
    > => {
      return signExecuteMethod(
        TestUpgradable,
        this,
        "getNewImmFieldsEncoded",
        params
      );
    },
    getNewMutFieldsEncoded: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getNewMutFieldsEncoded">
    ): Promise<
      TestUpgradableTypes.SignExecuteMethodResult<"getNewMutFieldsEncoded">
    > => {
      return signExecuteMethod(
        TestUpgradable,
        this,
        "getNewMutFieldsEncoded",
        params
      );
    },
    getImmValue: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getImmValue">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"getImmValue">> => {
      return signExecuteMethod(TestUpgradable, this, "getImmValue", params);
    },
    getMutValue: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"getMutValue">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"getMutValue">> => {
      return signExecuteMethod(TestUpgradable, this, "getMutValue", params);
    },
    setMutValue: async (
      params: TestUpgradableTypes.SignExecuteMethodParams<"setMutValue">
    ): Promise<TestUpgradableTypes.SignExecuteMethodResult<"setMutValue">> => {
      return signExecuteMethod(TestUpgradable, this, "setMutValue", params);
    },
  };

  async multicall<Calls extends TestUpgradableTypes.MultiCallParams>(
    calls: Calls
  ): Promise<TestUpgradableTypes.MultiCallResults<Calls>> {
    return (await multicallMethods(
      TestUpgradable,
      this,
      calls,
      getContractByCodeHash
    )) as TestUpgradableTypes.MultiCallResults<Calls>;
  }
}
